### PR TITLE
fix for app.asar

### PR DESCRIPTION
**Pull request by SNRSE**

### CODE REVIEW

**Comment by Sumolari** [comment]
@SNRSE, I think there’s been a mistake because after merging this PR there will be no modifications to the codebase. Could you double check the commits included in the PR, please?

**Comment by SNRSE** [comment]
ah just saw that seems like there is a problem with my git i past the fix here so you cayn iplement it how you like it:
Basicly you just need to change the path where ffprobe is to : ffprobePath.replace('app.asar','app.asar.unpacked');

**Comment by Sumolari** [comment]
@SNRSE I'm happy to do that but I feel uncomfortable adding a fix without having a way to reproduce the bug. Could you provide a way to reproduce the issue in Travis so we can prevent the error from being reintroduced in the future?

**Comment by SNRSE** [comment]
I don't think that Travis can test it. Basically, it's a problem when you build an app with Electron. You then Package this app into an asar ( app.asar) some files need to be outside to get executed and are transferred to app.ansar.unpacked. FFprobe is one of this that's why you need to change the path from app.asar/... to app.asar.unpacked/...

**Comment by Sumolari** [comment]
@SNRSE Could you post an example of the complete ffprobe path you get in an Electron app? I'm worried just replacing `app.asar` with `app.asar.unpacked`, might break non-electron users who are running code from a path including `app.asar`.

For instance if I'm running a regular Node.js script from `/server/sumolari-app.asar-production/`, just replacing `app.asar` with `app.asar.unpacked` would break the server.

I would prefer having some regular expression to minimize the probabilities of detecting a Node.js app as an Electron app.

**Comment by SNRSE** [comment]
Would maybe doing a fork especially for electron make sense?
________________________________

**Comment by Sumolari** [comment]
That's another solution. If you prefer going that way let me know if I could help you.

**Comment by SNRSE** [comment]
I have never published something to npm. So I need to look into how to do that.  Also, it seems the linter isn't happy with the change I did so need to investigate that.

**Comment by SNRSE** [comment]
Hey, is it may be possible that you do a fork with the changed line for the path? I have not yet figured out how to fork it and upload it to npm. Would be great if you help me

**Comment by Sumolari** [comment]
I don't want to publish an NPM package I cannot give support to and since I don't use Electron I won't be able to support the package properly (that's also why I don't  want to put a fix for Electron in this repository unless I have a proper automated test to avoid regressions).

Forking the repo and publishing the fork in NPM requires a few steps:

1. First, fork the repo, which you already did ([ByteHive/get-video-duration](https://github.com/ByteHive/get-video-duration)).
2. [Sign up in NPM](https://www.npmjs.com/signup) and create an account if you don't have one already.
3. Sign in with NPM cli, you can do this running `npm login` in a terminal window.
4. Update the `name` property in `package.json`. NPM uses this name when publishing and it must be unique. You could use `get-video-duration-electron` or a scope-based  name like `@ByteHive/get-video-duration`.
5. Publish the package using `npm publish`.

These instructions are explained in depth in [NPM documentation](https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages).

(I'm closing the PR as it has no changes but feel free the continue the conversation in the comments if you need so)

**Pull request closed without merging**
